def chars(str) = __intrinsic__("StringChars", str)
def size(str) = __intrinsic__("StringSize", str)
def from_chars(chars) = __intrinsic__("StringFromChars", chars)
def from_int(int) = __intrinsic__("StringFromInt", int)
def split(str, sep) = __intrinsic__("StringSplit", str, sep)